name: Tassion
favicon: null
layout_spectrum: 0.35609
typography_spectrum: 0.86531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#103e5f'
    - '#187890'
    - '#4fbec9'
    - '#9296e6'
  brandStrength: 0.4375
  lightness: 0.5141004309989512
  saturation: 0.17087072925642133
  rhythmicContrast: 0.41284950636327267
purpose: []
