name: Tassion
favicon: null
layout_spectrum: 0.5833782383706421
typography_spectrum: 0.1373653863556683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13499399786815047
  lightness: 0.5141004309989512
  saturation: 0.17087072925642133
  rhythmicContrast: 0.41284950636327267
purpose: []
