name: Tassion
favicon: null
layout_spectrum: 0.5833782383706421
typography_spectrum: 0.1373653863556683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3d2e31'
    - '#706063'
    - '#aab2fe'
    - '#0000f6'
  brandStrength: 0.375
  lightness: 0.5141004309989512
  saturation: 0.17087072925642133
  rhythmicContrast: 0.41284950636327267
purpose: []
